// <auto-generated />
using System;
using ASP_Quotes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP_Quotes.Migrations
{
    [DbContext(typeof(ASP_QuotesContext))]
    partial class ASP_QuotesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP_Quotes.Models.Quotes", b =>
                {
                    b.Property<int>("QuotesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<DateTime>("InsertDate");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("QuotesId");

                    b.ToTable("Quotes");

                    b.HasData(
                        new { QuotesId = 1, Author = "Вадим Зеланд", InsertDate = new DateTime(2020, 5, 29, 20, 39, 27, 471, DateTimeKind.Local), Text = "Чудо произойдет только в том случае, если вы сломаете привычный стереотип и будете думать не о средствах достижения, а о самой цели" },
                        new { QuotesId = 2, Author = "Вадим Зеланд", InsertDate = new DateTime(2020, 5, 29, 20, 39, 27, 495, DateTimeKind.Local), Text = "Вы никогда ничего не измените, если будете бороться с существующим. Чтобы что-то изменить, постройте новую модель и сделайте существующее устаревшим." },
                        new { QuotesId = 3, Author = "Генри Форд", InsertDate = new DateTime(2020, 5, 29, 20, 39, 27, 495, DateTimeKind.Local), Text = "Везет человеку, которому удается уйти из этого мира живым." },
                        new { QuotesId = 4, Author = "Альберт Эйнштейн", InsertDate = new DateTime(2020, 5, 29, 20, 39, 27, 495, DateTimeKind.Local), Text = "Я научился смотреть на смерть как на старый долг, который рано или поздно придется заплатить" },
                        new { QuotesId = 5, Author = "Кин Хаббард", InsertDate = new DateTime(2020, 5, 29, 20, 39, 27, 495, DateTimeKind.Local), Text = "Что бы там ни было, никогда не принимайте жизнь слишком всерьез – вам из нее живьем все равно не выбраться" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
